# Generated by Django 4.0.4 on 2022-06-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_bio_profile_profile_pic_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_date',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
